// Code generated by github.com/rajveermalviya/go-webgpu/cmd/gen_enums. DO NOT EDIT.

package wgpu

type AdapterType uint32

const (
	AdapterType_DiscreteGPU   AdapterType = 0
	AdapterType_IntegratedGPU AdapterType = 1
	AdapterType_CPU           AdapterType = 2
	AdapterType_Unknown       AdapterType = 3
)

type AddressMode uint32

const (
	AddressMode_Repeat       AddressMode = 0
	AddressMode_MirrorRepeat AddressMode = 1
	AddressMode_ClampToEdge  AddressMode = 2
)

type BackendType uint32

const (
	BackendType_Null     BackendType = 0
	BackendType_WebGPU   BackendType = 1
	BackendType_D3D11    BackendType = 2
	BackendType_D3D12    BackendType = 3
	BackendType_Metal    BackendType = 4
	BackendType_Vulkan   BackendType = 5
	BackendType_OpenGL   BackendType = 6
	BackendType_OpenGLES BackendType = 7
)

type BlendFactor uint32

const (
	BlendFactor_Zero              BlendFactor = 0
	BlendFactor_One               BlendFactor = 1
	BlendFactor_Src               BlendFactor = 2
	BlendFactor_OneMinusSrc       BlendFactor = 3
	BlendFactor_SrcAlpha          BlendFactor = 4
	BlendFactor_OneMinusSrcAlpha  BlendFactor = 5
	BlendFactor_Dst               BlendFactor = 6
	BlendFactor_OneMinusDst       BlendFactor = 7
	BlendFactor_DstAlpha          BlendFactor = 8
	BlendFactor_OneMinusDstAlpha  BlendFactor = 9
	BlendFactor_SrcAlphaSaturated BlendFactor = 10
	BlendFactor_Constant          BlendFactor = 11
	BlendFactor_OneMinusConstant  BlendFactor = 12
)

type BlendOperation uint32

const (
	BlendOperation_Add             BlendOperation = 0
	BlendOperation_Subtract        BlendOperation = 1
	BlendOperation_ReverseSubtract BlendOperation = 2
	BlendOperation_Min             BlendOperation = 3
	BlendOperation_Max             BlendOperation = 4
)

type BufferBindingType uint32

const (
	BufferBindingType_Undefined       BufferBindingType = 0
	BufferBindingType_Uniform         BufferBindingType = 1
	BufferBindingType_Storage         BufferBindingType = 2
	BufferBindingType_ReadOnlyStorage BufferBindingType = 3
)

type BufferMapAsyncStatus uint32

const (
	BufferMapAsyncStatus_Success                 BufferMapAsyncStatus = 0
	BufferMapAsyncStatus_Error                   BufferMapAsyncStatus = 1
	BufferMapAsyncStatus_Unknown                 BufferMapAsyncStatus = 2
	BufferMapAsyncStatus_DeviceLost              BufferMapAsyncStatus = 3
	BufferMapAsyncStatus_DestroyedBeforeCallback BufferMapAsyncStatus = 4
	BufferMapAsyncStatus_UnmappedBeforeCallback  BufferMapAsyncStatus = 5
)

type BufferUsage uint32

const (
	BufferUsage_None         BufferUsage = 0
	BufferUsage_MapRead      BufferUsage = 1
	BufferUsage_MapWrite     BufferUsage = 2
	BufferUsage_CopySrc      BufferUsage = 4
	BufferUsage_CopyDst      BufferUsage = 8
	BufferUsage_Index        BufferUsage = 16
	BufferUsage_Vertex       BufferUsage = 32
	BufferUsage_Uniform      BufferUsage = 64
	BufferUsage_Storage      BufferUsage = 128
	BufferUsage_Indirect     BufferUsage = 256
	BufferUsage_QueryResolve BufferUsage = 512
)

type ColorWriteMask uint32

const (
	ColorWriteMask_None  ColorWriteMask = 0
	ColorWriteMask_Red   ColorWriteMask = 1
	ColorWriteMask_Green ColorWriteMask = 2
	ColorWriteMask_Blue  ColorWriteMask = 4
	ColorWriteMask_Alpha ColorWriteMask = 8
	ColorWriteMask_All   ColorWriteMask = 15
)

type CompareFunction uint32

const (
	CompareFunction_Undefined    CompareFunction = 0
	CompareFunction_Never        CompareFunction = 1
	CompareFunction_Less         CompareFunction = 2
	CompareFunction_LessEqual    CompareFunction = 3
	CompareFunction_Greater      CompareFunction = 4
	CompareFunction_GreaterEqual CompareFunction = 5
	CompareFunction_Equal        CompareFunction = 6
	CompareFunction_NotEqual     CompareFunction = 7
	CompareFunction_Always       CompareFunction = 8
)

type CompilationInfoRequestStatus uint32

const (
	CompilationInfoRequestStatus_Success    CompilationInfoRequestStatus = 0
	CompilationInfoRequestStatus_Error      CompilationInfoRequestStatus = 1
	CompilationInfoRequestStatus_DeviceLost CompilationInfoRequestStatus = 2
	CompilationInfoRequestStatus_Unknown    CompilationInfoRequestStatus = 3
)

type CompilationMessageType uint32

const (
	CompilationMessageType_Error   CompilationMessageType = 0
	CompilationMessageType_Warning CompilationMessageType = 1
	CompilationMessageType_Info    CompilationMessageType = 2
)

type ComputePassTimestampLocation uint32

const (
	ComputePassTimestampLocation_Beginning ComputePassTimestampLocation = 0
	ComputePassTimestampLocation_End       ComputePassTimestampLocation = 1
)

type CreatePipelineAsyncStatus uint32

const (
	CreatePipelineAsyncStatus_Success         CreatePipelineAsyncStatus = 0
	CreatePipelineAsyncStatus_Error           CreatePipelineAsyncStatus = 1
	CreatePipelineAsyncStatus_DeviceLost      CreatePipelineAsyncStatus = 2
	CreatePipelineAsyncStatus_DeviceDestroyed CreatePipelineAsyncStatus = 3
	CreatePipelineAsyncStatus_Unknown         CreatePipelineAsyncStatus = 4
)

type CullMode uint32

const (
	CullMode_None  CullMode = 0
	CullMode_Front CullMode = 1
	CullMode_Back  CullMode = 2
)

type DeviceLostReason uint32

const (
	DeviceLostReason_Undefined DeviceLostReason = 0
	DeviceLostReason_Destroyed DeviceLostReason = 1
)

type ErrorFilter uint32

const (
	ErrorFilter_Validation  ErrorFilter = 0
	ErrorFilter_OutOfMemory ErrorFilter = 1
)

type ErrorType uint32

const (
	ErrorType_NoError     ErrorType = 0
	ErrorType_Validation  ErrorType = 1
	ErrorType_OutOfMemory ErrorType = 2
	ErrorType_Unknown     ErrorType = 3
	ErrorType_DeviceLost  ErrorType = 4
)

type FeatureName uint32

const (
	FeatureName_Undefined               FeatureName = 0
	FeatureName_DepthClipControl        FeatureName = 1
	FeatureName_Depth24UnormStencil8    FeatureName = 2
	FeatureName_Depth32FloatStencil8    FeatureName = 3
	FeatureName_TimestampQuery          FeatureName = 4
	FeatureName_PipelineStatisticsQuery FeatureName = 5
	FeatureName_TextureCompressionBC    FeatureName = 6
	FeatureName_TextureCompressionETC2  FeatureName = 7
	FeatureName_TextureCompressionASTC  FeatureName = 8
	FeatureName_IndirectFirstInstance   FeatureName = 9
)

type FilterMode uint32

const (
	FilterMode_Nearest FilterMode = 0
	FilterMode_Linear  FilterMode = 1
)

type FrontFace uint32

const (
	FrontFace_CCW FrontFace = 0
	FrontFace_CW  FrontFace = 1
)

type IndexFormat uint32

const (
	IndexFormat_Undefined IndexFormat = 0
	IndexFormat_Uint16    IndexFormat = 1
	IndexFormat_Uint32    IndexFormat = 2
)

type LoadOp uint32

const (
	LoadOp_Undefined LoadOp = 0
	LoadOp_Clear     LoadOp = 1
	LoadOp_Load      LoadOp = 2
)

type LogLevel uint32

const (
	LogLevel_Off   LogLevel = 0
	LogLevel_Error LogLevel = 1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Info  LogLevel = 3
	LogLevel_Debug LogLevel = 4
	LogLevel_Trace LogLevel = 5
)

type MapMode uint32

const (
	MapMode_None  MapMode = 0
	MapMode_Read  MapMode = 1
	MapMode_Write MapMode = 2
)

type MipmapFilterMode uint32

const (
	MipmapFilterMode_Nearest MipmapFilterMode = 0
	MipmapFilterMode_Linear  MipmapFilterMode = 1
)

type NativeFeature uint32

const NativeFeature_TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES NativeFeature = 268435456

type PipelineStatisticName uint32

const (
	PipelineStatisticName_VertexShaderInvocations   PipelineStatisticName = 0
	PipelineStatisticName_ClipperInvocations        PipelineStatisticName = 1
	PipelineStatisticName_ClipperPrimitivesOut      PipelineStatisticName = 2
	PipelineStatisticName_FragmentShaderInvocations PipelineStatisticName = 3
	PipelineStatisticName_ComputeShaderInvocations  PipelineStatisticName = 4
)

type PowerPreference uint32

const (
	PowerPreference_Undefined       PowerPreference = 0
	PowerPreference_LowPower        PowerPreference = 1
	PowerPreference_HighPerformance PowerPreference = 2
)

type PredefinedColorSpace uint32

const (
	PredefinedColorSpace_Undefined PredefinedColorSpace = 0
	PredefinedColorSpace_Srgb      PredefinedColorSpace = 1
)

type PresentMode uint32

const (
	PresentMode_Immediate PresentMode = 0
	PresentMode_Mailbox   PresentMode = 1
	PresentMode_Fifo      PresentMode = 2
)

type PrimitiveTopology uint32

const (
	PrimitiveTopology_PointList     PrimitiveTopology = 0
	PrimitiveTopology_LineList      PrimitiveTopology = 1
	PrimitiveTopology_LineStrip     PrimitiveTopology = 2
	PrimitiveTopology_TriangleList  PrimitiveTopology = 3
	PrimitiveTopology_TriangleStrip PrimitiveTopology = 4
)

type QueryType uint32

const (
	QueryType_Occlusion          QueryType = 0
	QueryType_PipelineStatistics QueryType = 1
	QueryType_Timestamp          QueryType = 2
)

type QueueWorkDoneStatus uint32

const (
	QueueWorkDoneStatus_Success    QueueWorkDoneStatus = 0
	QueueWorkDoneStatus_Error      QueueWorkDoneStatus = 1
	QueueWorkDoneStatus_Unknown    QueueWorkDoneStatus = 2
	QueueWorkDoneStatus_DeviceLost QueueWorkDoneStatus = 3
)

type RenderPassTimestampLocation uint32

const (
	RenderPassTimestampLocation_Beginning RenderPassTimestampLocation = 0
	RenderPassTimestampLocation_End       RenderPassTimestampLocation = 1
)

type RequestAdapterStatus uint32

const (
	RequestAdapterStatus_Success     RequestAdapterStatus = 0
	RequestAdapterStatus_Unavailable RequestAdapterStatus = 1
	RequestAdapterStatus_Error       RequestAdapterStatus = 2
	RequestAdapterStatus_Unknown     RequestAdapterStatus = 3
)

type RequestDeviceStatus uint32

const (
	RequestDeviceStatus_Success RequestDeviceStatus = 0
	RequestDeviceStatus_Error   RequestDeviceStatus = 1
	RequestDeviceStatus_Unknown RequestDeviceStatus = 2
)

type SamplerBindingType uint32

const (
	SamplerBindingType_Undefined    SamplerBindingType = 0
	SamplerBindingType_Filtering    SamplerBindingType = 1
	SamplerBindingType_NonFiltering SamplerBindingType = 2
	SamplerBindingType_Comparison   SamplerBindingType = 3
)

type ShaderStage uint32

const (
	ShaderStage_None     ShaderStage = 0
	ShaderStage_Vertex   ShaderStage = 1
	ShaderStage_Fragment ShaderStage = 2
	ShaderStage_Compute  ShaderStage = 4
)

type StencilOperation uint32

const (
	StencilOperation_Keep           StencilOperation = 0
	StencilOperation_Zero           StencilOperation = 1
	StencilOperation_Replace        StencilOperation = 2
	StencilOperation_Invert         StencilOperation = 3
	StencilOperation_IncrementClamp StencilOperation = 4
	StencilOperation_DecrementClamp StencilOperation = 5
	StencilOperation_IncrementWrap  StencilOperation = 6
	StencilOperation_DecrementWrap  StencilOperation = 7
)

type StorageTextureAccess uint32

const (
	StorageTextureAccess_Undefined StorageTextureAccess = 0
	StorageTextureAccess_WriteOnly StorageTextureAccess = 1
)

type StoreOp uint32

const (
	StoreOp_Undefined StoreOp = 0
	StoreOp_Store     StoreOp = 1
	StoreOp_Discard   StoreOp = 2
)

type TextureAspect uint32

const (
	TextureAspect_All         TextureAspect = 0
	TextureAspect_StencilOnly TextureAspect = 1
	TextureAspect_DepthOnly   TextureAspect = 2
)

type TextureComponentType uint32

const (
	TextureComponentType_Float           TextureComponentType = 0
	TextureComponentType_Sint            TextureComponentType = 1
	TextureComponentType_Uint            TextureComponentType = 2
	TextureComponentType_DepthComparison TextureComponentType = 3
)

type TextureDimension uint32

const (
	TextureDimension_1D TextureDimension = 0
	TextureDimension_2D TextureDimension = 1
	TextureDimension_3D TextureDimension = 2
)

type TextureFormat uint32

const (
	TextureFormat_Undefined            TextureFormat = 0
	TextureFormat_R8Unorm              TextureFormat = 1
	TextureFormat_R8Snorm              TextureFormat = 2
	TextureFormat_R8Uint               TextureFormat = 3
	TextureFormat_R8Sint               TextureFormat = 4
	TextureFormat_R16Uint              TextureFormat = 5
	TextureFormat_R16Sint              TextureFormat = 6
	TextureFormat_R16Float             TextureFormat = 7
	TextureFormat_RG8Unorm             TextureFormat = 8
	TextureFormat_RG8Snorm             TextureFormat = 9
	TextureFormat_RG8Uint              TextureFormat = 10
	TextureFormat_RG8Sint              TextureFormat = 11
	TextureFormat_R32Float             TextureFormat = 12
	TextureFormat_R32Uint              TextureFormat = 13
	TextureFormat_R32Sint              TextureFormat = 14
	TextureFormat_RG16Uint             TextureFormat = 15
	TextureFormat_RG16Sint             TextureFormat = 16
	TextureFormat_RG16Float            TextureFormat = 17
	TextureFormat_RGBA8Unorm           TextureFormat = 18
	TextureFormat_RGBA8UnormSrgb       TextureFormat = 19
	TextureFormat_RGBA8Snorm           TextureFormat = 20
	TextureFormat_RGBA8Uint            TextureFormat = 21
	TextureFormat_RGBA8Sint            TextureFormat = 22
	TextureFormat_BGRA8Unorm           TextureFormat = 23
	TextureFormat_BGRA8UnormSrgb       TextureFormat = 24
	TextureFormat_RGB10A2Unorm         TextureFormat = 25
	TextureFormat_RG11B10Ufloat        TextureFormat = 26
	TextureFormat_RGB9E5Ufloat         TextureFormat = 27
	TextureFormat_RG32Float            TextureFormat = 28
	TextureFormat_RG32Uint             TextureFormat = 29
	TextureFormat_RG32Sint             TextureFormat = 30
	TextureFormat_RGBA16Uint           TextureFormat = 31
	TextureFormat_RGBA16Sint           TextureFormat = 32
	TextureFormat_RGBA16Float          TextureFormat = 33
	TextureFormat_RGBA32Float          TextureFormat = 34
	TextureFormat_RGBA32Uint           TextureFormat = 35
	TextureFormat_RGBA32Sint           TextureFormat = 36
	TextureFormat_Stencil8             TextureFormat = 37
	TextureFormat_Depth16Unorm         TextureFormat = 38
	TextureFormat_Depth24Plus          TextureFormat = 39
	TextureFormat_Depth24PlusStencil8  TextureFormat = 40
	TextureFormat_Depth24UnormStencil8 TextureFormat = 41
	TextureFormat_Depth32Float         TextureFormat = 42
	TextureFormat_Depth32FloatStencil8 TextureFormat = 43
	TextureFormat_BC1RGBAUnorm         TextureFormat = 44
	TextureFormat_BC1RGBAUnormSrgb     TextureFormat = 45
	TextureFormat_BC2RGBAUnorm         TextureFormat = 46
	TextureFormat_BC2RGBAUnormSrgb     TextureFormat = 47
	TextureFormat_BC3RGBAUnorm         TextureFormat = 48
	TextureFormat_BC3RGBAUnormSrgb     TextureFormat = 49
	TextureFormat_BC4RUnorm            TextureFormat = 50
	TextureFormat_BC4RSnorm            TextureFormat = 51
	TextureFormat_BC5RGUnorm           TextureFormat = 52
	TextureFormat_BC5RGSnorm           TextureFormat = 53
	TextureFormat_BC6HRGBUfloat        TextureFormat = 54
	TextureFormat_BC6HRGBFloat         TextureFormat = 55
	TextureFormat_BC7RGBAUnorm         TextureFormat = 56
	TextureFormat_BC7RGBAUnormSrgb     TextureFormat = 57
	TextureFormat_ETC2RGB8Unorm        TextureFormat = 58
	TextureFormat_ETC2RGB8UnormSrgb    TextureFormat = 59
	TextureFormat_ETC2RGB8A1Unorm      TextureFormat = 60
	TextureFormat_ETC2RGB8A1UnormSrgb  TextureFormat = 61
	TextureFormat_ETC2RGBA8Unorm       TextureFormat = 62
	TextureFormat_ETC2RGBA8UnormSrgb   TextureFormat = 63
	TextureFormat_EACR11Unorm          TextureFormat = 64
	TextureFormat_EACR11Snorm          TextureFormat = 65
	TextureFormat_EACRG11Unorm         TextureFormat = 66
	TextureFormat_EACRG11Snorm         TextureFormat = 67
	TextureFormat_ASTC4x4Unorm         TextureFormat = 68
	TextureFormat_ASTC4x4UnormSrgb     TextureFormat = 69
	TextureFormat_ASTC5x4Unorm         TextureFormat = 70
	TextureFormat_ASTC5x4UnormSrgb     TextureFormat = 71
	TextureFormat_ASTC5x5Unorm         TextureFormat = 72
	TextureFormat_ASTC5x5UnormSrgb     TextureFormat = 73
	TextureFormat_ASTC6x5Unorm         TextureFormat = 74
	TextureFormat_ASTC6x5UnormSrgb     TextureFormat = 75
	TextureFormat_ASTC6x6Unorm         TextureFormat = 76
	TextureFormat_ASTC6x6UnormSrgb     TextureFormat = 77
	TextureFormat_ASTC8x5Unorm         TextureFormat = 78
	TextureFormat_ASTC8x5UnormSrgb     TextureFormat = 79
	TextureFormat_ASTC8x6Unorm         TextureFormat = 80
	TextureFormat_ASTC8x6UnormSrgb     TextureFormat = 81
	TextureFormat_ASTC8x8Unorm         TextureFormat = 82
	TextureFormat_ASTC8x8UnormSrgb     TextureFormat = 83
	TextureFormat_ASTC10x5Unorm        TextureFormat = 84
	TextureFormat_ASTC10x5UnormSrgb    TextureFormat = 85
	TextureFormat_ASTC10x6Unorm        TextureFormat = 86
	TextureFormat_ASTC10x6UnormSrgb    TextureFormat = 87
	TextureFormat_ASTC10x8Unorm        TextureFormat = 88
	TextureFormat_ASTC10x8UnormSrgb    TextureFormat = 89
	TextureFormat_ASTC10x10Unorm       TextureFormat = 90
	TextureFormat_ASTC10x10UnormSrgb   TextureFormat = 91
	TextureFormat_ASTC12x10Unorm       TextureFormat = 92
	TextureFormat_ASTC12x10UnormSrgb   TextureFormat = 93
	TextureFormat_ASTC12x12Unorm       TextureFormat = 94
	TextureFormat_ASTC12x12UnormSrgb   TextureFormat = 95
)

type TextureSampleType uint32

const (
	TextureSampleType_Undefined         TextureSampleType = 0
	TextureSampleType_Float             TextureSampleType = 1
	TextureSampleType_UnfilterableFloat TextureSampleType = 2
	TextureSampleType_Depth             TextureSampleType = 3
	TextureSampleType_Sint              TextureSampleType = 4
	TextureSampleType_Uint              TextureSampleType = 5
)

type TextureUsage uint32

const (
	TextureUsage_None             TextureUsage = 0
	TextureUsage_CopySrc          TextureUsage = 1
	TextureUsage_CopyDst          TextureUsage = 2
	TextureUsage_TextureBinding   TextureUsage = 4
	TextureUsage_StorageBinding   TextureUsage = 8
	TextureUsage_RenderAttachment TextureUsage = 16
)

type TextureViewDimension uint32

const (
	TextureViewDimension_Undefined TextureViewDimension = 0
	TextureViewDimension_1D        TextureViewDimension = 1
	TextureViewDimension_2D        TextureViewDimension = 2
	TextureViewDimension_2DArray   TextureViewDimension = 3
	TextureViewDimension_Cube      TextureViewDimension = 4
	TextureViewDimension_CubeArray TextureViewDimension = 5
	TextureViewDimension_3D        TextureViewDimension = 6
)

type VertexFormat uint32

const (
	VertexFormat_Undefined VertexFormat = 0
	VertexFormat_Uint8x2   VertexFormat = 1
	VertexFormat_Uint8x4   VertexFormat = 2
	VertexFormat_Sint8x2   VertexFormat = 3
	VertexFormat_Sint8x4   VertexFormat = 4
	VertexFormat_Unorm8x2  VertexFormat = 5
	VertexFormat_Unorm8x4  VertexFormat = 6
	VertexFormat_Snorm8x2  VertexFormat = 7
	VertexFormat_Snorm8x4  VertexFormat = 8
	VertexFormat_Uint16x2  VertexFormat = 9
	VertexFormat_Uint16x4  VertexFormat = 10
	VertexFormat_Sint16x2  VertexFormat = 11
	VertexFormat_Sint16x4  VertexFormat = 12
	VertexFormat_Unorm16x2 VertexFormat = 13
	VertexFormat_Unorm16x4 VertexFormat = 14
	VertexFormat_Snorm16x2 VertexFormat = 15
	VertexFormat_Snorm16x4 VertexFormat = 16
	VertexFormat_Float16x2 VertexFormat = 17
	VertexFormat_Float16x4 VertexFormat = 18
	VertexFormat_Float32   VertexFormat = 19
	VertexFormat_Float32x2 VertexFormat = 20
	VertexFormat_Float32x3 VertexFormat = 21
	VertexFormat_Float32x4 VertexFormat = 22
	VertexFormat_Uint32    VertexFormat = 23
	VertexFormat_Uint32x2  VertexFormat = 24
	VertexFormat_Uint32x3  VertexFormat = 25
	VertexFormat_Uint32x4  VertexFormat = 26
	VertexFormat_Sint32    VertexFormat = 27
	VertexFormat_Sint32x2  VertexFormat = 28
	VertexFormat_Sint32x3  VertexFormat = 29
	VertexFormat_Sint32x4  VertexFormat = 30
)

type VertexStepMode uint32

const (
	VertexStepMode_Vertex   VertexStepMode = 0
	VertexStepMode_Instance VertexStepMode = 1
)
